### ISSUE TITLE
Unable to see preceding test page, while testing with ELB endpoint

### ISSUE THREAD

**Issue by cvamsikrishna11** [PacktPublishing/Implementing-DevOps-on-AWS#1]
Hi, 
I am working on Chapter 3, Terraform files. I have deployed the terraform, AWS infrastructure was created, but when I am checking with ELB DNS I am getting HTTP 503 error. Could please help me with this.

**Comment by gaurav-packt** [comment]
If the issue still exists kindly reopen the issue.
