### ISSUE TITLE
RollBack issue

### ISSUE THREAD

**Issue by AJVA2580** [PacktPublishing/Implementing-DevOps-on-AWS#2]
Hello, 

First of all a very interesting book.  I have been trying to fall along and I am getting this message while I am trying to deploy the first main.json template. 

Parameter validation failed: parameter value cloudformation for parameter name autoscalingGroupKeyname does not exist. Rollback requested by user.
--

{
    "ParameterKey": "autoscalingGroupKeyname",
    "ParameterValue": "cloudformation"
  },

Any subjections about what is the possible issue - Thanking you in advances for your help

**Comment by packt-pradeeps** [comment]
Please reopen the issue if it still persists.
